spring.application.name=studyspace

spring.security.oauth2.client.registration.google.client-id=594899481207-h6c1bvlrrt7jo7jqeqp4muof23lj205t.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=
# spring.security.oauth2.client.registration.google.scope=https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/userinfo.email
spring.security.oauth2.client.registration.google.scope=profile, email, https://www.googleapis.com/auth/contacts.readonly
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
